# Generated by Django 2.1.7 on 2019-04-22 12:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('srn', models.CharField(default='', max_length=13)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('email', models.EmailField(default='', max_length=254)),
                ('pno', models.IntegerField(default=0)),
                ('ppno', models.IntegerField(default=0)),
                ('field', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME')], default='CSE', max_length=3)),
                ('address', models.TextField()),
                ('lg_name', models.CharField(max_length=100)),
                ('lg_age', models.IntegerField(default=0)),
                ('lg_dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('lg_pno', models.IntegerField(default=0)),
                ('lg_address', models.TextField()),
            ],
        ),
    ]
